version: "3.8"

services:

  dev:
    image: 16nsk/devcontainer-php
    volumes:
      - dev:/workspace
    command: sleep infinity
    ports:
      - "3000:3000"
      - "8000:8000"
      - "8080:8080"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  dev:
  db:
