version: "3.8"

services:

  dev:
    image: 16nsk/devcontainer-php
    build: .
    volumes:
      - dev:/workspace
    command: sleep infinity
    ports:
      - "3000:3000"
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=developer
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mail:
    image: 'mailhog/mailhog'
    environment:
      MH_STORAGE: maildir
    volumes:
      - ./.docker/maildir:/maildir
    ports:
      - 8025:8025

volumes:
  dev:
  mysql:
  elasticsearch:
  redis:
